ifdef::env-github[:outfilesuffix: .adoc]

AI Web Git Deployment Method
============================

One of the supported methods for deploying your code onto the Agile
Infrastructure is to set up a Git instance on the webserver and push to that
instance. There is a hook that runs when this instance receives a git push that
deploys/updates the content of the git repository into a folder that is apache's
document-root. This way updating the website code integrates almost trivially
into a git workflow, and it is also the simplest and most flexible method of
doing deployment in a repeatable and controlled manner.

Git Deploy
----------

Each instance (dev, test, production) will have have a path (https://<your-url>/git/)
that is the target that you can git-push to. You can specify to the person
coordinating the migration a path you wish to be populated with the contents of
the git repo on that machine.

For example, if your application runs under apache and the documentroot lives in
/var/www/myapp, then a git-push to the url https://<your-service>/git/ will
populate the folder /var/www/myapp with the contents of the most recent git
snapshot.

Architecture
~~~~~~~~~~~~

Assumptions::
. You are familiar with basic concepts of git, specifically _branches_ and
  _remotes_
. Your code is in a git repository on your local development machine
. You have a version of git >= 1.7.2
. There may (should) be a remote known as "origin" that you develop with

Each backend instance will serve as a different. I recommend naming
them something sane like _dev-deploy_, _test-deploy_, and _deploy_. Each remote
only allows one branch called _master_, which you should create first.

Work on your local master branch and when the time comes to deploy, create a
remote and a tracking branch

Limitations
~~~~~~~~~~~

Only one branch is allowed, called "master". This is because these instances
should *not* be the main copy of your git repo, and furthermore, only one branch
can exist checked out as the actual instance of your application.
