ifdef::env-github[:outfilesuffix: .adoc]

AI Web Git Deployment Method
============================

One of the supported methods for deploying your code onto the Agile
Infrastructure is to set up a Git instance on the webserver and push to that
instance. There is a hook that runs when this instance receives a git push that
deploys/updates the content of the git repository into a folder that is apache's
document-root. This way updating the website code integrates almost trivially
into a git workflow, and it is also the simplest and most flexible method of
doing deployment in a repeatable and controlled manner.

NOTE: If you are using SLC6 on LXPlus <<old-git-version,see here>>

Git Deploy
----------

Each instance (dev, test, production) will have have a path (https://<your-url>/git/)
that is the target that you can git-push to. You can specify to the person
coordinating the migration a path you wish to be populated with the contents of
the git repo on that machine.

For example, if your application runs under apache and the documentroot lives in
/var/www/myapp, then a git-push to the url https://<your-service>/git/ will
populate the folder /var/www/myapp with the contents of the most recent git
snapshot.

The access to the git repository will only be granted to the service owner and
anyone they designate (all need a CERN acct.). You will authenticate with your
standard Username & Password at CERN

Architecture
~~~~~~~~~~~~

Assumptions::
. You are familiar with basic concepts of git, specifically _branches_ and
  _remotes_
. Your code is in a git repository on your local development machine
. You have a version of git >= '1.7.2' (or have > '1.6.5' but < '1.7.2' and
have read <<old-git-version,this>>).
. There may (should) be a remote known as "origin" that you develop with

Each backend instance will serve as a different. I recommend naming
them something sane like _dev-deploy_, _test-deploy_, and _deploy_. Each remote
only allows one branch called _master_, which you should create first.

Work on your local master branch and when the time comes to deploy, create a
remote and a tracking branch for that remote for each instance you will be
working on. Merge your changes into this branch then push it to it's remote and
you're done!

Limitations
~~~~~~~~~~~

Only one branch is allowed, called "master". This is because these instances
should *not* be the main copy of your git repo, and furthermore, only one branch
can exist checked out as the actual instance of your application.

Non-fast-forward commits *are* allowed, so be careful, and don't _push -f_
unless you really mean it!

Old Git Version
~~~~~~~~~~~~~~~

Read this if you are stuck with git '1.7.1' (the unfortunate default on 'SLC6'
and on *lxplus*) or are having issues

There are a few things to know when working from an older version of git. First
and foremost is that you _need_ to put your username in the URL, before the host
just like when using curl +<proto>://<user>:<password>@<host>/<url>+ where the
password is optional. For example I would use
+https://wstrecke@example.cern.ch/git/+ as a repository URL.

The second thing is that it appears that CERN certs are not trusted by
lubcurl/nss/openssl by default. Have
http://stackoverflow.com/a/11622001[a look here] for various ways to disable
SSL Certificate checking in git.

The second thing is that if you don't include your password in the URL, you need
to either ensure you are logged in with X-forwarding, or you need to run +unset
SSH_ASKPASS+ (or your favorite shell's equivalent) to ensure you don't get an X
window popup to ask for your password.

In summary:

. Encode username in URL prior to the hostname separated by an '@' sign
. Be prepared for an X window popup or unset the environment variable
  +SSH_ASKPASS+
. Either trust CERN-signed certs, or tell git not to check cert-provenance via
  either the environment variable +GIT_SSL_NO_VERIFY+, or globally disable in
  your gitconfig 'git config http.sslVerify false', or globally by adding a
  '--global' flag to the previous commit (writes your ~/.gitconfig file).

Example
-------

The following is an example of a very simple work flow where you simply push
your main working branch to a new remote

---------
$ whoami
wstrecke
$ git clone https://git.cern.ch<whereever>/your-project
...
$ cd your-project/

/* make changes to your main branch -- we'll call it 'main' to differentiate it
 * from the 'master' branch on the deployment servers, but it is likely called
 * master
 */
$ ...work...

$ git status
On branch main
...

/* Be sure to include username if using an older git version */
$ git remote add dev-deploy https://wstrecke@example-dev.cern.ch/git/exampleservice/

/* Nothing happens here if first time, just checking connectivity / access */
$ git fetch dev-deploy

/* publish <your-branch>:<their-branch>, if first time it will be created */
$ git push dev-deploy main:master
...
 * [new branch]      main -> master

/* follow same steps for test instance and production instances, changing URL
 * and remote name as appropriate
 */
$ ...keep working...

---------

If you have the code somewhere else and don't want to use git as part of the
workflow at all, you can make a copy of the code somewhere, run +git init+, and
then commit & push. Like the following example:

-------
$ cp -a ~/svn/your-app ~/gitapp
$ cd ~/gitapp
$ git init
$ git add .
$ git commit -m 'first commit'
$ git push https://username@app-foo-dev.cern.ch/git/example/ master:master
-------
