ifdef::env-github[:outfilesuffix: .adoc]

AI Web RPM Deployment
=====================

You can build an RPM of your source files and put it into a repository that
Puppet will ensure the latest version is installed from.

This means to update your website's code you just rebuild the RPM and place the
packages in the repo.

Dependencies
------------

If you build an RPM you can specify any dependent packages and as long as they
are placed in the repository they will be installed when your service is.


Requirements
------------

Your RPM _must_ conform to http://fedoraproject.org/wiki/Packaging:Guidelines[
RedHat's packaging guidelines]

Your application should be self-contained, in other words, with the exception of
configuration files, it should exist under one directory. Your RPM can place the
application anywhere that isn't a folder already controlled by another RPM --
the docroot for your webapp can be made any folder (for example, '/var/www/
html' is a *bad* place since it is already owned by the 'httpd' package, but for
example '/var/www/foo' is fine)


How To
------

An RPM is built with the combination of a .spec-file and a tarball containing
your code. https://fedoraproject.org/wiki/How_to_create_an_RPM_package[Here is
some] documentation on how to create an RPM from scratch.

Your RPM should be simple, basically a glorified-tarball--it shouldn't install
any files outside of the documentroot of the website and it shouldn't have any
pre- or post-scripts that do configuration. The only thing besides deploying the
code that it should do is to specify any dependencies.
