ifdef::env-github[:outfilesuffix: .adoc]

Backend Setup
=============

This doc will cover the configuration of the backend-services, especially
what is in common between them and the base-configuration.

Service-Base Configuration
--------------------------

The backends share the https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/servicebase.pp[
hg_voatlasmisc::servicebase] code in servicebase.pp. This code ensures the basics
are there, like AFS, apache, any sudoers access, and firewall rules.


Access Control Hierarchy
~~~~~~~~~~~~~~~~~~~~~~~~

Access control is done with several hiera variables. First and foremost, for staff,
adc-central-services can log in as root (via +rootegroups+ in hiera) and
interactively (via +sssd::interactiveallowgroups+). Furthermore, the people in
https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/base/vomisc.pp[
base/vomisc.pp] have sudo access.

The users are given login access either through an egroup or by listing their
usernames in hiera (under +sssd::interactiveallow*+). The set of people allowed
to 'sudo' to root is the +servicebase::sudo+ variable, with a default of those
named in +sssd::interactiveallowusers+.

If git-deployment is used, the list of people allowed to push to the site-code
git-repo are those set in the +servicebase::gitusers+ variable, with a default
of those allowed to 'sudo' (see above paragraph).

As a summary, see this table:

.Granting User Permissions
[width="50%",cols=">s,^2m,^2e",frame="topbot",options="header"]
|==========================
|Access Type | Variable  | Fallback (default)
|Login       | sssd::interactiveallowusers  | None (membership in egroup
if +sssd::interactiveallowgroups+ is defined)
|Sudo        | servicebase::sudo  | +sssd::interactiveallowusers+
|Git         | servicebase::gitusers  | Those with Sudo access
|==========================


Apache Settings
---------------

Each backend has their own web-configuration needs, which are reflected in the
various vhost configurations in the backend code. We use the upstream puppetlabs-
apache module that is quite powerful and flexible. See the code for various
examples of the +apache::vhost+ directive ranging from
https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/trig_cost.pp[
quite simple] to https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/larmon.pp[
a bit more complex].

One setting common to all is the fragment +LimitRequestFieldSize 262144+ which
allows much larger headers to be passed from the redirector. This is needed
because the EGroups field that gets filled out by Shibboleth can be very large
and there is a limit of 8Kb http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestfieldsize[
by default] on the size of a single header from apache.


Data Volume Management
----------------------

Many services have a +/data+ volume (and one or two have /var/lib/mysql volumes)
that is a separate filesystem (a cinder volume in OpenStack). This volume
is attached to the production instance of the services, while the other
instances have just a +/data+ folder.

This volume must be attached with +nova volume-attach+, but the mounting of
the filesystem and the +/etc/fstab+ entry is managed in puppet. There is a
parameter in Foreman called "web_instance_type" that when set to the value
"prod", instructs the filesystem to be mounted there and an +/etc/fstab+ entry
to be created.

*WARNING*: If this parameter is removed, absent, or changed from "prod", and
there is a data-volume mounted there, it will be unmounted and removed from
+/etc/fstab+ (actually, +umount+ will be run, but if there are open files on
the device it will fail and require manual intervention).

The code to manage this is in https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/servicebase/mount_point.pp[
servicebase/mount_point.pp] in voatlasmisc. For an example of how to use it
see the usage in https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/atlasdcs.pp[
atlasdcs.pp].

Creating a volume is done through the +cinder+ command, and attaching is done
with +nova+. When moving a volume from one machine to another, all unmounting
operations should be complete (if triggered by puppet or by hand) before
detaching the volume to avoid corruption.

Deployment Methods
------------------

Deploying to the backend is done with either git or by hand (or RPMs, but nobody
so far has chosen to do so). To enable RPM deployed sites in puppet it is simply
a matter of putting the yum-repo where the site code is in place on the
backends and ensuring the package is set to latest.

Using git-deployment has been a popular option. Each instance of each service
gets a git-URL in it's namespace. This is by default <service-name>/git/<repo-name>,
like 'https://atlas-larmon.cern.ch/git/larmon'. The redirector configuration for
this setup is discussed  link:redirector{outfilesuffix}#git-url[here].

Git deployment in puppet is taken care of on the backend by including the
https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/servicebase/gitdeploy.pp[
servicebase/gitdeploy.pp] class. The following two parameters are frequently
set:

. +reponame+, the name of the git-repo in the URL after the '/git/' portion (often named after the service)
. +deploydir+, the folder to be managed by git (often the docroot of the site)

Git Management Detail
~~~~~~~~~~~~~~~~~~~~~

For git-managed sites the docroot of the site must be owned by apache since
this directory is managed by the
https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/templates/servicebase/gitdeploy_update.erb[
git update hook] (run by apache).
There is a mild security implication here, but any other option would have
required the use of a custom setuid-wrapper that checked out the files as root.

The blank repo is created by puppet when the machine is built, again visible in the
servicebase/gitdeploy.pp class (the +git init --bare+ Exec[] resource)


Apache Config
^^^^^^^^^^^^^

The git-deployment is managed through a separate apache virtual host on the
backend (port 8443) that is mapped through the /git URLs on the redirector (see
link:redirector{outfilesuffix}#git-url[this section] of the redirector docs.
This vhost uses CERN Kerberos auth to allow the user command-line authentication
needed by git (SSO wouldn't work).


Update Hook
^^^^^^^^^^^

The actual deployment is done via the https://www.kernel.org/pub/software/scm/git/docs/githooks.html#update[
'update' hook] on the backend's git repo. The update hook runs git force-checkout
in the web application's document-root. *WARNING*: for this reason, the site
should not store any dynamic data under the docroot, as it will be wiped out
by a subsequent git-push.

This hook also blocks the creation and deletion of branches other than master,
which is to discourage using these repos as a ``upstream'' source for the
site's code. This is because it is not backed up and should only be used as
a deployment method, not as a place to develop from.



Backend TODO
------------

. Enable the firewall to only open ports 80/443/8443 to the redirectors
  For this to work well we need puppetdbquery() to work or we need to use
  exported resources (possibly?), neither of which is the case now.
