ifdef::env-github[:outfilesuffix: .adoc]

Redirector Setup
================

This doc will cover the configuration of the web redirectors themselves

Redirector Architecture
-----------------------

There are currently 3 production redirectors:

. _aiatlas-webredirector_
. _aiatlas090_
. _aiatlas091_

(don't ask about the first name!) and 1 test redirector:

. _atlas-test-redir_

The test redirector is only accessible from within CERN while the other ones
have firewall conduits for 80/443 that *need to be maintained yearly*.

Access
~~~~~~

The redirector has no AFS, and only root can log in. This is accomplished by
setting root_egroups to adc-central-services in the
https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/data/hostgroup/voatlasmisc/redirector/web.yaml[
hiera file] for the redirector.

Security
~~~~~~~~

As mentioned above, there are outward-facing firewall conduits for 80/443, so
these machiens need to remain patched and have their apache-configuration
secured. *These conduits need to be maintained yearly.*

These nodes also terminate SSL connections, and the certificates for each
service are generated with puppet +certmgr+ class. Since each service has
one or more instances (dev, test, prod), the certs are generated with Subject
Alt-Name (SAN) fields containing all the service names. This is visible at the
bottom of https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/tree/refs/heads/ai_prod:/code/manifests/redirector/webservice.pp[
redirector/webservice.pp] in the voatlasmisc repo. Having multiple virtual
hosts with different SSL certs on the same IP/Port requires clients to support
https://en.wikipedia.org/wiki/Server_Name_Indication[SNI], which has been
standard for over 10 years now, so only Windows XP clients are excluded.


Instances
~~~~~~~~~

The redirector has ope or more virtual hosts for each instance of each service.
A standard SSL-encrypted services has one virtual host on port 80 that just
redirects to the https instance on port 443. The puppet code for these instances
can be https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/code/manifests/redirector/instance.pp[
found here] -- see the comments at the top for the various knobs available.

Git URL
^^^^^^^

If Git-deployment is used, the https-instance of the site will proxy the /git
URL to a link:backends{outfilesuffix}#apache-config[different backend vhost].

This URL has no SSO-auth on the redirector even if SSO is used, as it is
handled by the puppet-created virtual-host config on the backend (using CERN
Kerberos auth).

Even if the site is http-only the git-URL will be proxied through https because
the username/password is given with the kerberos-auth used on the backend.


Shibboleth Setup
----------------

As covered link:../admin{outfilesuffix}#puppet-architecture[here], the puppet-environments we use use
https://git.cern.ch/web/it-puppet-module-shibboleth.git/shortlog/refs/heads/wstrecke_shib[
the +wstrecke_shib+ branch] of the shibboleth module, which enables
multiple-services in one shibboleth instance. This branch should probably get
pushed upstream someday...

The shibboleth module uses a hash in hiera called +shibboleth_multi_service+
that maps SSO-Id to SSO-host, like:

----
shibboleth_multi_service:
    atlas-migration-example:  "atlas-example.cern.ch"
    atlas-trig-cost:          "atlas-trig-cost.cern.ch
----

Where +atlas-migration-example+ is the registered SSO Application-id and
+"atlas-example.cern.ch"+ is the service-name.

See https://git.cern.ch/web/it-puppet-hostgroup-voatlasmisc.git/blob/refs/heads/ai_prod:/data/hostgroup/voatlasmisc/redirector/web.yaml[
redirector/web.yaml] in the voatlasmsic repo for the configuration.

The apache configuration if using SSO contains the setting 'LimitRequestFieldSize
262144' which is required since the EGroups header can be larger than the
default of 8Kb.




Future Work: Load Balancing
---------------------------

Ideally, the redirector would be a load-balanced cluster where the first name
would be the entry-point. Each _aiatlas09X_ redirector would be in the cluster.

There are two problems with this approach that I don't know how to solve right
now.

1. There is a limit of 255 characters for the list of aliases given to a node
   in DNS. The totality of CNAME aliases needed for the various backends is far
   larger than 255 characters, hence the 3 redirectors.
   +
   We would need a way to manage a much larger number of CNAME aliases that
   resolve to the DNS name of the load-balancer.

2. Shibboleth sessions are stored by default in-memory per-redirector. This
   means that if you were to resolve a different redirector from the alias
   you'd be required to re-auth. The easiest way I see to solve this is to use
   a database-backed
   https://itservices.stanford.edu/service/shibboleth/sp/sharedsession[shared
   session cache]. However this would introduce another dependency (the db) and
   a possible single-point-of-failure. Another option would be to use memcached,
   but this has the same drawbacks as a database.
